id = "darcula-dark-okkano"
name = "Darcula Dark Theme - Okkano Version"
description = "A dark theme inspired by IntelliJ IDEA's Darcula theme"
version = "0.1.2"
schema_version = 1
authors = ["Okan KARAMAN <karamanokan@msn.com>"]
repository = "https://github.com/okkan/zed-darcula-dark-okkano"

[themes]
darcula-dark-okkano = "themes/darcula-dark-okkano.json"
